[package]
name = "CSV"
authors = ["Mark Rickert [https://github.com/markrickert]", "mooff [https://github.com/togetherbeer]"]
version = "0.0.9"
homepage = "https://github.com/togetherbeer/dragonruby-csv"
keywords = ["csv", "parser", "generator", "parse", "generate", "comma", "separator", "file", "format", "io"]

# documentation = "https://example.com"
repository = "https://github.com/togetherbeer/dragonruby-csv"

# Which files do you want to be automatically required from your package.
requires = ["lib/stringio.rb", "lib/dragonruby-csv.rb"]

[package.installs]
# <from> = <to>
# "lib/library.rb" = "app/lib/library.rb"

[dragonruby]
version = "2"
edition = "standard"

